version: "3.9"

services:
  n-gpt:
    build: .
    container_name: n-gpt
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "8001:8000"
    networks:
      - johngear_shared_net

networks:
  johngear_shared_net:
    external: true